# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestLogin():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_login(self):
    # Test name: login
    # Step # | name | target | value
    # 1 | open | http://10.255.255.1/ck2/index.php?mod=auth&a=signout | 
    self.driver.get("http://10.255.255.1/ck2/index.php?mod=auth&a=signout")
    # 2 | setWindowSize | 1382x744 | 
    self.driver.set_window_size(1382, 744)
    # 3 | click | linkText=CK2 Dev manager | 
    self.driver.find_element(By.LINK_TEXT, "CK2 Dev manager").click()
    # 4 | type | id=c2f3e133 | ck2test1
    self.driver.find_element(By.ID, "c2f3e133").send_keys("ck2test1")
    # 5 | type | id=ecadc3fd | test123
    self.driver.find_element(By.ID, "ecadc3fd").send_keys("test123")
    # 6 | click | id=c17d6c39 | 
    self.driver.find_element(By.ID, "c17d6c39").click()
    # 7 | click | css=a > span | 
    self.driver.find_element(By.CSS_SELECTOR, "a > span").click()
    # 8 | click | linkText=Sign Out | 
    self.driver.find_element(By.LINK_TEXT, "Sign Out").click()
    # 9 | click | linkText=CK2 Dev manager | 
    self.driver.find_element(By.LINK_TEXT, "CK2 Dev manager").click()
    # 10 | type | id=c2f3e133 | 123123
    self.driver.find_element(By.ID, "c2f3e133").send_keys("123123")
    # 11 | click | id=ecadc3fd | 
    self.driver.find_element(By.ID, "ecadc3fd").click()
    # 12 | type | id=ecadc3fd | 123123
    self.driver.find_element(By.ID, "ecadc3fd").send_keys("123123")
    # 13 | click | id=c17d6c39 | 
    self.driver.find_element(By.ID, "c17d6c39").click()
  
