# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDeleteitemlist():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_deleteitemlist(self):
    # Test name: delete item list
    # Step # | name | target | value
    # 1 | open | http://10.255.255.1/ck2/?mod=auth&a=signin&redir=%2Fck2%2Findex.php%3F | 
    self.driver.get("http://10.255.255.1/ck2/?mod=auth&a=signin&redir=%2Fck2%2Findex.php%3F")
    # 2 | setWindowSize | 1382x744 | 
    self.driver.set_window_size(1382, 744)
    # 3 | type | id=c2f3e133 | ck2test
    self.driver.find_element(By.ID, "c2f3e133").send_keys("ck2test")
    # 4 | type | id=ecadc3fd | test123
    self.driver.find_element(By.ID, "ecadc3fd").send_keys("test123")
    # 5 | click | id=c2f3e133 | 
    self.driver.find_element(By.ID, "c2f3e133").click()
    # 6 | type | id=c2f3e133 | ck2test1
    self.driver.find_element(By.ID, "c2f3e133").send_keys("ck2test1")
    # 7 | click | id=c17d6c39 | 
    self.driver.find_element(By.ID, "c17d6c39").click()
    # 8 | click | linkText=Penjualan | 
    self.driver.find_element(By.LINK_TEXT, "Penjualan").click()
    # 9 | click | linkText=SL/202204/000027 | 
    self.driver.find_element(By.LINK_TEXT, "SL/202204/000027").click()
    # 10 | click | id=right-pane_f54e1119 | 
    self.driver.find_element(By.ID, "right-pane_f54e1119").click()
    # 11 | click | css=#\_modal #\_modal_bdb60c6b | 
    self.driver.find_element(By.CSS_SELECTOR, "#\\_modal #\\_modal_bdb60c6b").click()
    # 12 | runScript | window.scrollTo(0,0) | 
    self.driver.execute_script("window.scrollTo(0,0)")
    # 13 | click | name=ff778ac3-select[] | 
    self.driver.find_element(By.NAME, "ff778ac3-select[]").click()
    # 14 | click | id=a5d036ad | 
    self.driver.find_element(By.ID, "a5d036ad").click()
    # 15 | click | id=ba8173ff | 
    self.driver.find_element(By.ID, "ba8173ff").click()
    # 16 | click | css=#\_modal #\_modal_aae1dc42 | 
    self.driver.find_element(By.CSS_SELECTOR, "#\\_modal #\\_modal_aae1dc42").click()
    # 17 | click | css=.material-icons:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".material-icons:nth-child(2)").click()
    # 18 | click | css=.activity-body | 
    self.driver.find_element(By.CSS_SELECTOR, ".activity-body").click()
    # 19 | click | css=a > span | 
    self.driver.find_element(By.CSS_SELECTOR, "a > span").click()
    # 20 | click | linkText=Sign Out | 
    self.driver.find_element(By.LINK_TEXT, "Sign Out").click()
  
