# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestVoid():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_void(self):
    # Test name: void
    # Step # | name | target | value
    # 1 | open | http://10.255.255.1/ck2/?mod=auth&a=signin&redir=%2Fck2%2Findex.php%3F | 
    self.driver.get("http://10.255.255.1/ck2/?mod=auth&a=signin&redir=%2Fck2%2Findex.php%3F")
    # 2 | setWindowSize | 1382x744 | 
    self.driver.set_window_size(1382, 744)
    # 3 | type | id=c2f3e133 | ck2test1
    self.driver.find_element(By.ID, "c2f3e133").send_keys("ck2test1")
    # 4 | type | id=ecadc3fd | test123
    self.driver.find_element(By.ID, "ecadc3fd").send_keys("test123")
    # 5 | click | id=c17d6c39 | 
    self.driver.find_element(By.ID, "c17d6c39").click()
    # 6 | click | linkText=Penjualan | 
    self.driver.find_element(By.LINK_TEXT, "Penjualan").click()
    # 7 | click | linkText=SL/202204/000028 | 
    self.driver.find_element(By.LINK_TEXT, "SL/202204/000028").click()
    # 8 | mouseOver | id=right-pane_cecc656a | 
    element = self.driver.find_element(By.ID, "right-pane_cecc656a")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 9 | mouseOut | id=right-pane_cecc656a | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 10 | mouseOver | id=right-pane_acc5561e | 
    element = self.driver.find_element(By.ID, "right-pane_acc5561e")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 11 | click | id=right-pane_acc5561e | 
    self.driver.find_element(By.ID, "right-pane_acc5561e").click()
    # 12 | mouseOut | id=right-pane_acc5561e | 
    element = self.driver.find_element(By.CSS_SELECTOR, "body")
    actions = ActionChains(self.driver)
    actions.move_to_element(element, 0, 0).perform()
    # 13 | click | css=#\_form-sales_void #\_modal_ee79d1ac | 
    self.driver.find_element(By.CSS_SELECTOR, "#\\_form-sales_void #\\_modal_ee79d1ac").click()
    # 14 | click | linkText=Penjualan | 
    self.driver.find_element(By.LINK_TEXT, "Penjualan").click()
    # 15 | click | id=e7dbc346 | 
    self.driver.find_element(By.ID, "e7dbc346").click()
    # 16 | select | id=e7dbc346 | label=Void
    dropdown = self.driver.find_element(By.ID, "e7dbc346")
    dropdown.find_element(By.XPATH, "//option[. = 'Void']").click()
    # 17 | click | css=#fef301d7 > .material-icons | 
    self.driver.find_element(By.CSS_SELECTOR, "#fef301d7 > .material-icons").click()
    # 18 | click | css=.material-icons:nth-child(2) | 
    self.driver.find_element(By.CSS_SELECTOR, ".material-icons:nth-child(2)").click()
    # 19 | click | linkText=Sign Out | 
    self.driver.find_element(By.LINK_TEXT, "Sign Out").click()
  
