# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestAdditem():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_additem(self):
    # Test name: add item
    # Step # | name | target | value
    # 1 | open | http://10.255.255.1/ck2/?mod=auth&a=signin&redir=%2Fck2%2Findex.php%3F | 
    self.driver.get("http://10.255.255.1/ck2/?mod=auth&a=signin&redir=%2Fck2%2Findex.php%3F")
    # 2 | setWindowSize | 1382x744 | 
    self.driver.set_window_size(1382, 744)
    # 3 | type | id=c2f3e133 | ck2test1
    self.driver.find_element(By.ID, "c2f3e133").send_keys("ck2test1")
    # 4 | click | id=ecadc3fd | 
    self.driver.find_element(By.ID, "ecadc3fd").click()
    # 5 | type | id=ecadc3fd | test123
    self.driver.find_element(By.ID, "ecadc3fd").send_keys("test123")
    # 6 | click | id=c17d6c39 | 
    self.driver.find_element(By.ID, "c17d6c39").click()
    # 7 | click | linkText=Penjualan | 
    self.driver.find_element(By.LINK_TEXT, "Penjualan").click()
    # 8 | click | linkText=SL/202204/000027 | 
    self.driver.find_element(By.LINK_TEXT, "SL/202204/000027").click()
    # 9 | click | css=#right-pane_f8933034 > .material-icons | 
    self.driver.find_element(By.CSS_SELECTOR, "#right-pane_f8933034 > .material-icons").click()
    # 10 | click | linkText=qr_code_2 0000000933117 | 
    self.driver.find_element(By.LINK_TEXT, "qr_code_2 0000000933117").click()
    # 11 | click | id=_modal_c2cee85c | 
    self.driver.find_element(By.ID, "_modal_c2cee85c").click()
    # 12 | click | id=right-pane_ee310ab4 | 
    self.driver.find_element(By.ID, "right-pane_ee310ab4").click()
    # 13 | click | id=ba8173ff | 
    self.driver.find_element(By.ID, "ba8173ff").click()
    # 14 | click | css=#\_modal #\_modal_aae1dc42 | 
    self.driver.find_element(By.CSS_SELECTOR, "#\\_modal #\\_modal_aae1dc42").click()
    # 15 | click | css=a > span | 
    self.driver.find_element(By.CSS_SELECTOR, "a > span").click()
    # 16 | click | linkText=Sign Out | 
    self.driver.find_element(By.LINK_TEXT, "Sign Out").click()
  
