# Generated by Selenium IDE
from contextlib import aclosing
from http.client import OK
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestBuatpenjualanbaru():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()OK or object (aclosing)
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_buatpenjualanbaru(self):
    # Test name: Buat penjualan baru
    # Step # | name | target | value
    # 1 | open | http://10.255.255.1/ck2/?mod=auth&a=signin&redir=%2Fck2%2Findex.php%3F | 
    self.driver.get("http://10.255.255.1/ck2/?mod=auth&a=signin&redir=%2Fck2%2Findex.php%3F")
    # 2 | setWindowSize | 1346x708 | 
    self.driver.set_window_size(1346, 708)
    # 3 | type | id=c2f3e133 | ck2test1
    self.driver.find_element(By.ID, "c2f3e133").send_keys("ck2test1")
    # 4 | type | id=ecadc3fd | test123
    self.driver.find_element(By.ID, "ecadc3fd").send_keys("test123")
    # 5 | click | id=c17d6c39 | 
    self.driver.find_element(By.ID, "c17d6c39").click()
    # 6 | click | id=vi9bwu-acc-menu-link | 
    self.driver.find_element(By.ID, "vi9bwu-acc-menu-link").click()
    # 7 | click | linkText=Buat Penjualan Baru | 
    self.driver.find_element(By.LINK_TEXT, "Buat Penjualan Baru").click()
    # 8 | click | id=dc814a9e | 
    self.driver.find_element(By.ID, "dc814a9e").click()
    # 9 | select | id=dc814a9e | label=01 - Aep Suyatman
    dropdown = self.driver.find_element(By.ID, "dc814a9e")
    dropdown.find_element(By.XPATH, "//option[. = '01 - Aep Suyatman']").click()
    # 10 | click | id=bc7938e6 | 
    self.driver.find_element(By.ID, "bc7938e6").click()
    # 11 | type | id=bc7938e6 | 12314265234
    self.driver.find_element(By.ID, "bc7938e6").send_keys("12314265234")
    # 12 | click | id=b2a7aff7 | 
    self.driver.find_element(By.ID, "b2a7aff7").click()
    # 13 | click | id=c63b8ddd | 
    self.driver.find_element(By.ID, "c63b8ddd").click()
    # 14 | mouseOver | id=c63b8ddd | 
    element = self.driver.find_element(By.ID, "c63b8ddd")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 15 | click | linkText=Bpk Akiong/Kimtio | 
    self.driver.find_element(By.LINK_TEXT, "Bpk Akiong/Kimtio").click()
    # 16 | mouseDownAt | id=_modal_ca7b70b0 | 17.765625,16
    element = self.driver.find_element(By.ID, "_modal_ca7b70b0")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 17 | mouseMoveAt | css=.activity-body:nth-child(3) | 1100.5,-8.1875
    element = self.driver.find_element(By.CSS_SELECTOR, ".activity-body:nth-child(3)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 18 | mouseUpAt | css=.activity-body:nth-child(3) | 1100.5,-8.1875
    element = self.driver.find_element(By.CSS_SELECTOR, ".activity-body:nth-child(3)")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 19 | click | css=#\_form-contact > #activity-header #activity-handler | 
    self.driver.find_element(By.CSS_SELECTOR, "#\\_form-contact > #activity-header #activity-handler").click()
    # 20 | click | id=_modal_c63aa623 | 
    self.driver.find_element(By.ID, "_modal_c63aa623").click()
    # 21 | click | id=abb83b35 | 
    self.driver.find_element(By.ID, "abb83b35").click()
    # 22 | type | id=abb83b35 | CUMA TEST
    self.driver.find_element(By.ID, "abb83b35").send_keys("CUMA TEST")
    # 23 | click | id=b988f087 | 
    self.driver.find_element(By.ID, "b988f087").click()
    # 24 | type | id=b988f087 | 5,055,555
    self.driver.find_element(By.ID, "b988f087").send_keys("5,055,555")
    # 25 | click | id=dc094c05 | 
    self.driver.find_element(By.ID, "dc094c05").click()
    # 26 | mouseDownAt | css=#\_modal #\_modal_e152dbe3 | 87.359375,21.5
    element = self.driver.find_element(By.CSS_SELECTOR, "#\\_modal #\\_modal_e152dbe3")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).click_and_hold().perform()
    # 27 | mouseMoveAt | css=#\_modal #\_modal_e152dbe3 | 87.359375,21.5
    element = self.driver.find_element(By.CSS_SELECTOR, "#\\_modal #\\_modal_e152dbe3")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).perform()
    # 28 | mouseUpAt | css=#\_modal #\_modal_e152dbe3 | 87.359375,21.5
    element = self.driver.find_element(By.CSS_SELECTOR, "#\\_modal #\\_modal_e152dbe3")
    actions = ActionChains(self.driver)
    actions.move_to_element(element).release().perform()
    # 29 | click | css=#\_modal #\_modal_e152dbe3 | 
    self.driver.find_element(By.CSS_SELECTOR, "#\\_modal #\\_modal_e152dbe3").click()
    # 30 | click | id=d4112a57 | 
    self.driver.find_element(By.ID, "d4112a57").click()
    # 31 | type | id=d4112a57 | Cuma test
    self.driver.find_element(By.ID, "d4112a57").send_keys("Cuma test")
    # 32 | click | id=a65ef3ec | 
    self.driver.find_element(By.ID, "a65ef3ec").click()
    # 33 | type | id=a65ef3ec | BCA
    self.driver.find_element(By.ID, "a65ef3ec").send_keys("BCA")
    # 34 | type | id=c06663a4 | Ayong
    self.driver.find_element(By.ID, "c06663a4").send_keys("Ayong")
    # 35 | type | id=d6b24dbd | 0129354123-98455
    self.driver.find_element(By.ID, "d6b24dbd").send_keys("0129354123-98455")
    # 36 | click | id=b2fbb97f | 
    self.driver.find_element(By.ID, "b2fbb97f").click()
    # 37 | click | id=a6ee32cb | 
    self.driver.find_element(By.ID, "a6ee32cb").click()
    # 38 | click | css=.is-dropdown-submenu-parent > a | 
    self.driver.find_element(By.CSS_SELECTOR, ".is-dropdown-submenu-parent > a").click()
    # 39 | click | linkText=Sign Out | 
    self.driver.find_element(By.LINK_TEXT, "Sign Out").click()
  
